/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import Controle.DadosPessoaisC;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ryan
 */
public class ConsultaPacMedV extends javax.swing.JFrame {
        DefaultTableModel campotabela=new DefaultTableModel();
        ResultSet resposta=null;
        DadosPessoaisC dadospessoaisc=new DadosPessoaisC();
    /**
     * Creates new form ConsultaPacMedV
     */
    public ConsultaPacMedV() {
        initComponents();
        campotabela.addColumn("NOME");
        campotabela.addColumn("CPF");
        campotabela.addColumn("RG");
        campotabela.addColumn("SEXO");
        campotabela.addColumn("DATA DE NASCIMENTO");
        campotabela.addColumn("EMAIL");
        campotabela.addColumn("FONE 1");
        campotabela.addColumn("FONE 2");
        JTablePessoas.setModel(campotabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTCpf = new javax.swing.JTextField();
        JBGeral = new javax.swing.JButton();
        JBPCpf = new javax.swing.JButton();
        JCBEscolha = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablePessoas = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Consulta Paciente/Medico");

        JTCpf.setText("Insira o CPF");
        JTCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTCpfFocusLost(evt);
            }
        });
        JTCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTCpfActionPerformed(evt);
            }
        });

        JBGeral.setText("Consulta Geral");
        JBGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGeralActionPerformed(evt);
            }
        });

        JBPCpf.setText("Consulta por CPF");
        JBPCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPCpfActionPerformed(evt);
            }
        });

        JCBEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pacientes", "medicos" }));
        JCBEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBEscolhaActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(JCBEscolha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(JBPCpf)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBPCpf)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBGeral)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        JTablePessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTablePessoas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCpfActionPerformed

    private void JBGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGeralActionPerformed
        if(JCBEscolha.getSelectedItem().toString()=="pacientes"){
                    try{
            resposta=dadospessoaisc.ConsultaPorPacienteGeral();
            int linha=0;
            //Percorre todas as linhas do ResultSet
            while(resposta.next()){
                //campotabela.setNumRows(linha+1);
                campotabela.setRowCount(linha+1);
                //Laço para percorrer as COLUNAS DA TABELA Registro
                for(int i=1;i<=8;i++){
                    if(i==1){
                        JTablePessoas.setValueAt(resposta.getArray(i), linha, i-1);
                    }
                    /* 
                    if(i==2){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    if(i==3){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    */
                    else
                        JTablePessoas.setValueAt(resposta.getString(i), linha, i-1);
                }
                linha++;
            }
        }catch(Exception erro){
            erro.printStackTrace();
        } 
        }  
        
    if(JCBEscolha.getSelectedItem().toString()=="medicos"){
        try{
            resposta=dadospessoaisc.ConsultaPorMedicoGeral();
            int linha=0;
            //Percorre todas as linhas do ResultSet
            while(resposta.next()){
                //campotabela.setNumRows(linha+1);
                campotabela.setRowCount(linha+1);
                //Laço para percorrer as COLUNAS DA TABELA Registro
                for(int i=1;i<=8;i++){
                    if(i==1){
                        JTablePessoas.setValueAt(resposta.getArray(i), linha, i-1);
                    }
                    /* 
                    if(i==2){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    if(i==3){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    */
                    else
                        JTablePessoas.setValueAt(resposta.getString(i), linha, i-1);
                }
                linha++;
            }
        }catch(Exception erro){
            erro.printStackTrace();
        } 
        }    // TODO add your handling code here:
    }//GEN-LAST:event_JBGeralActionPerformed

    private void JCBEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBEscolhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBEscolhaActionPerformed

    private void JTCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTCpfFocusGained
        JTCpf.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_JTCpfFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JTCpf.setText("Insira o cpf");  
        campotabela.setRowCount(0); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JBPCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPCpfActionPerformed
        if(JCBEscolha.getSelectedItem().toString()=="pacientes"){
        try{
            String cpf = JTCpf.getText() ;
            resposta=dadospessoaisc.ConsultaPorCPFPaciente(cpf);
            int linha=0;
            //Percorre todas as linhas do ResultSet
            while(resposta.next()){
                //campotabela.setNumRows(linha+1);
                campotabela.setRowCount(linha+1);
                //Laço para percorrer as COLUNAS DA TABELA Registro
                for(int i=1;i<=8;i++){
                    if(i==1){
                        JTablePessoas.setValueAt(resposta.getArray(i), linha, i-1);
                    }
                    /* 
                    if(i==2){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    if(i==3){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    */
                    else
                        JTablePessoas.setValueAt(resposta.getString(i), linha, i-1);
                }
                linha++;
            }
        }catch(Exception erro){
            erro.printStackTrace();
        } 
    }        
    if(JCBEscolha.getSelectedItem().toString()=="medicos"){
        try{
            String cpf = JTCpf.getText() ;
            resposta=dadospessoaisc.ConsultaPorCPFMedico(cpf);
            int linha=0;
            //Percorre todas as linhas do ResultSet
            while(resposta.next()){
                //campotabela.setNumRows(linha+1);
                campotabela.setRowCount(linha+1);
                //Laço para percorrer as COLUNAS DA TABELA Registro
                for(int i=1;i<=8;i++){
                    if(i==1){
                        JTablePessoas.setValueAt(resposta.getArray(i), linha, i-1);
                    }
                    /* 
                    if(i==2){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    if(i==3){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    */
                    else
                        JTablePessoas.setValueAt(resposta.getString(i), linha, i-1);
                }
                linha++;
            }
        }catch(Exception erro){
            erro.printStackTrace();
        } 
    }// TODO add your handling code here:
    }//GEN-LAST:event_JBPCpfActionPerformed

    private void JTCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTCpfFocusLost
        if(JTCpf.getText().trim().isEmpty()){
            JTCpf.setText("Insira o CPF");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_JTCpfFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacMedV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacMedV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacMedV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacMedV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPacMedV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGeral;
    private javax.swing.JButton JBPCpf;
    private javax.swing.JComboBox<String> JCBEscolha;
    private javax.swing.JTextField JTCpf;
    private javax.swing.JTable JTablePessoas;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
