/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import Controle.EnderecoC;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ryan
 */
public class ConsultaEnderecoV extends javax.swing.JFrame {
    DefaultTableModel campotabela=new DefaultTableModel();
        ResultSet respota = null;
        EnderecoC enderecoc=new EnderecoC();
    /**
     * Creates new form ConsultaEndereco
     */
    public ConsultaEnderecoV() {
        initComponents();
        campotabela.addColumn("RUA");
        campotabela.addColumn("NUMERO");
        campotabela.addColumn("BAIRRO");
        campotabela.addColumn("CIDADE");
        campotabela.addColumn("ESTADO");
        campotabela.addColumn("CEP");
        campotabela.addColumn("OBS");
        JTableEnderecos.setModel(campotabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableEnderecos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTCep = new javax.swing.JTextField();
        JBBuscarCep = new javax.swing.JButton();
        JBBuscaGeral = new javax.swing.JButton();
        JBLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTableEnderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JTableEnderecos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        jLabel1.setText("CONSULTAR ENDEREÇO");

        JTCep.setText("Inserir CEP");
        JTCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTCepFocusGained(evt);
            }
        });
        JTCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTCepActionPerformed(evt);
            }
        });

        JBBuscarCep.setText("Buscar por CEP");
        JBBuscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscarCepActionPerformed(evt);
            }
        });

        JBBuscaGeral.setText("Buscar Geral");
        JBBuscaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscaGeralActionPerformed(evt);
            }
        });

        JBLimpar.setText("Limpar");
        JBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTCep, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBBuscarCep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBBuscaGeral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBLimpar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(JTCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBBuscarCep)
                    .addComponent(JBBuscaGeral)
                    .addComponent(JBLimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarCepActionPerformed
        try{
            String cep = JTCep.getText() ;
            ResultSet resposta = enderecoc.ConsultaPorCEP(cep);
            int linha=0;
            //Percorre todas as linhas do ResultSet
            while(resposta.next()){
                //campotabela.setNumRows(linha+1);
                campotabela.setRowCount(linha+1);
                //Laço para percorrer as COLUNAS DA TABELA Registro
                for(int i=1;i<=7;i++){
                    if(i==1){
                        JTableEnderecos.setValueAt(resposta.getArray(i), linha, i-1);
                    }
                    /* 
                    if(i==2){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    if(i==3){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    */
                    else
                        JTableEnderecos.setValueAt(resposta.getString(i), linha, i-1);
                }
                linha++;
            }
        }catch(Exception erro){
            erro.printStackTrace();
        }         // TODO add your handling code here:
    }                                                                

    private void JBLIMPARActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JTCep.setText("Digite Cep");    
         campotabela.setRowCount(0);         // TODO add your handling code here:
    }//GEN-LAST:event_JBBuscarCepActionPerformed

    private void JBBuscaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscaGeralActionPerformed
        try{
            ResultSet resposta = enderecoc.ConsultaGeral();
            int linha=0;
            //Percorre todas as linhas do ResultSet
            while(resposta.next()){
                //campotabela.setNumRows(linha+1);
                campotabela.setRowCount(linha+1);
                //Laço para percorrer as COLUNAS DA TABELA Registro
                for(int i=1;i<=7;i++){
                    if(i==1){
                        JTableEnderecos.setValueAt(resposta.getArray(i), linha, i-1);
                    }
                    /* 
                    if(i==2){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    if(i==3){
                        jtableRA.setValueAt(resposta.getInt(i), linha, i-1);
                    }
                    */
                    else
                        JTableEnderecos.setValueAt(resposta.getString(i), linha, i-1);
                }
                linha++;
            }
        }catch(Exception erro){
            erro.printStackTrace();
        }          // TODO add your handling code here:
    }//GEN-LAST:event_JBBuscaGeralActionPerformed

    private void JBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimparActionPerformed
        JTCep.setText("Inserir Cep");   
         campotabela.setRowCount(0); 
        // TODO add your handling code here:
    }//GEN-LAST:event_JBLimparActionPerformed

    private void JTCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCepActionPerformed

    private void JTCepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTCepFocusGained
        JTCep.setText("");
            // TODO add your handling code here:
    }//GEN-LAST:event_JTCepFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaEnderecoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaEnderecoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaEnderecoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaEnderecoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaEnderecoV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBuscaGeral;
    private javax.swing.JButton JBBuscarCep;
    private javax.swing.JButton JBLimpar;
    private javax.swing.JTextField JTCep;
    private javax.swing.JTable JTableEnderecos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
